### ISSUE TITLE
Labels of linked root-level menus are not propoerly displayed

### ISSUE THREAD

**Issue by 0x10** [0x10/obmenu2#17]
If the following XML is opened with obmenu2, the label of the menu with id "test1" is not shown properly.
Instead obmenu2 shows "???" (most of the time).

`<openbox_menu>
<menu id="test1" label="not shown">
<item label="empty" />
</menu>
<menu id="root-menu" label="Openbox 3">
<menu id="test1" />
</menu>
</openbox_menu>`

**Comment by saltasatelites** [comment]
I see the issue is closed, but the problem is still the same.
