### ISSUE TITLE
 Feature Request: Package the app

### ISSUE THREAD

**Issue by root2185** [0x10/obmenu2#19]
Hi, thanks for this app.

Can you add the necessary things to make `obmenu2` like a package?
An icon, a .desktop file, maybe a man page with a brief explanation and other things if there are.

This is the .desktop, inspired by obconf, that I placed in `usr/share/applications`:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Openbox Menu Manager
Keywords=openbox;menu;
Comment=Tweak Openbox Menu
Icon=obmenu2
Exec=obmenu2 %f
Categories=Settings;DesktopSettings;GTK;
StartupNotify=true
Terminal=false
```
For example you can use a make a file that installs things locally:
```
# Where to put executable commands on ’make install’? 
BIN = /usr/local/bin 
# Where to put icons on ’make instal 
ICONS = /usr/local/share/obmenu2
```
Then the distro devs will eventually package it.

**Comment by Scorpion2185** [comment]
Surely you can take my .dekstop.
For the icon I took the obconf-qt one and I just changed the color of the border, the quality is not the best (as the original).
From `/usr/share/icons/hicolor/48x48/apps`.
![obmenu2](https://user-images.githubusercontent.com/32654091/138347350-97e16270-8632-4cea-b18f-3ea59c6436c1.png)

**Comment by 0x10** [comment]
Unfortunately I can't use this icon due to attribution and licensing. Thank you very much.
I quickly created my own. So this issue should be done?

**Comment by root2185** [comment]
It seems so I already made a request for package to Debian devs, since I use Debian.

**Comment by root2185** [comment]
Did you forget the `obmenu2.desktop` file in the `Makefile`?

Do you know what are the packages required on Debian, to use `obmenu2`?
