### ISSUE TITLE
Label in Root menu showing ???

### ISSUE THREAD

**Issue by dglava** [0x10/obmenu2#2]
The label field for the top menu is showing "???" instead of the linked menu's name.

https://i.ibb.co/9bK46RG/2020-05-02-14-25-28.png

The menu.xml file used: https://pastebin.com/hRPDDyWL

**Comment by 0x10** [comment]
Thank you. 
The issue occurs due to the missing default namespace. I will fix this in xml loading.

**Comment by 0x10** [comment]
Should be fixed now.
