### ISSUE TITLE
THANKS A LOT! :-) It saves my day and everything can stay that way

### ISSUE THREAD

**Issue by pm-pm** [0x10/obmenu2#21]
Hello,
after upgrading today a (remote) virtual machine from buster to bullseye only a few things did not work. I was really happy that so much is working after the upgrade. I had bad experience in the past.

But after i found out that the important tool **obmenu** doesn't work and there is no replacement i was shocked, because parts of the project would have had to be rebuilt. But I don't want anything different from what it is now.

By the way, one comment please:
My server has been running for over 10 years with the same tasks. There are no changes in content. The server should only do its job. BUT I have to do this upgrade madness every 2 years. PHP no longer works, any libs no longer work. Sometimes this, sometimes that.

This has to stop! There are applications where you don't change anything for 10 years. Why these upgrades? For new features? Ok, but I don't need new features!

But current versions should be used for security reasons. But why do they have to become incompatible?

Waterfox wants a new glibc, cups has problems with Samsung printers since the last update and so on. So if you install the "small" updates, everything doesn't work together anymore and you have to upgrade to the next Debian version. :-(

So a BIG THANK YOU to the developer of this tool. It saves a lot of nerves because now I don't have to come up with a new concept for the menus. Everything can stay as familiar!

THANK YOU! :-)
pm-pm

PS:
I do not know how much work it is to make an official Debian repository, but maybe more work than programming this tool.

**Comment by 0x10** [comment]
You're welcome :)
Thanks for your kind words. I'm glad I saved someones day at least once in my life.

I can understand your frustration about unnecessary feature bloated software updates. I'm suffering from that as well, but I have no proper solution either.

I have no clue about debian packaging or hosting a repository. I guess it will be easier if you just create a little cron job executed monthly or better yearly, with a single "git pull" for this repository...
Besides a working python 3 environment and a gtk python binding, there aren't much dependencies. If they will break some day and I take note, I will fix it.
